[package]
edition.workspace = true
name              = "vprogs-state-ptr-rollback"
version.workspace = true

[dependencies]
vprogs-core-types.workspace      = true
vprogs-state-space.workspace     = true
vprogs-storage-manager.workspace = true
vprogs-storage-types.workspace   = true
