[package]
edition.workspace = true
name              = "vprogs-transaction-runtime-object-id"
version.workspace = true

[dependencies]
borsh.workspace                              = true
vprogs-transaction-runtime-address.workspace = true
