[package]
edition.workspace = true
name              = "vprogs-node-framework"
version.workspace = true

[dependencies]
arc-swap.workspace                    = true
log.workspace                         = true
tokio.workspace                       = true
vprogs-core-atomics.workspace         = true
vprogs-node-l1-bridge.workspace       = true
vprogs-scheduling-scheduler.workspace = true
vprogs-state-space.workspace          = true
vprogs-storage-manager.workspace      = true
vprogs-storage-types.workspace        = true
