[package]
edition.workspace = true
name              = "vprogs-node-vm"
version.workspace = true

[dependencies]
vprogs-scheduling-scheduler.workspace                    = true
vprogs-state-space.workspace                             = true
vprogs-storage-types.workspace                           = true
vprogs-transaction-runtime.workspace                     = true
vprogs-transaction-runtime-error.workspace               = true
vprogs-transaction-runtime-object-access.workspace       = true
vprogs-transaction-runtime-object-id.workspace           = true
vprogs-transaction-runtime-transaction.workspace         = true
vprogs-transaction-runtime-transaction-effects.workspace = true
