[package]
edition.workspace = true
name              = "vprogs-transaction-runtime-builtin-capabilities"
version.workspace = true

[dependencies]
vprogs-transaction-runtime-address.workspace = true
vprogs-transaction-runtime-data.workspace    = true
