[package]
edition.workspace = true
name              = "vprogs-transaction-runtime-data-context"
version.workspace = true

[dependencies]
vprogs-transaction-runtime-address.workspace            = true
vprogs-transaction-runtime-authenticated-data.workspace = true
vprogs-transaction-runtime-error.workspace              = true
