[package]
edition.workspace = true
name              = "vprogs-storage-rocksdb-store"
version.workspace = true

[dependencies]
num_cpus.workspace             = true
rocksdb.workspace              = true
tap.workspace                  = true
vprogs-state-space.workspace   = true
vprogs-storage-types.workspace = true
