[package]
edition.workspace = true
name              = "vprogs-core-macros"
version.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace       = true
syn.workspace         = true
