[package]
edition = "2021"
name    = "vprogs-node-l1-bridge"
version = "0.1.0"

[dependencies]
crossbeam-queue = "0.3.12"
futures         = "0.3"
log             = "0.4"
thiserror       = "2"
tokio           = { version = "1", features = ["rt", "sync"] }
workflow-core   = "0.18.0"

kaspa-consensus-core = { git = "https://github.com/kaspanet/rusty-kaspa", branch = "master" }
kaspa-notify         = { git = "https://github.com/kaspanet/rusty-kaspa", branch = "master" }
kaspa-rpc-core       = { git = "https://github.com/kaspanet/rusty-kaspa", branch = "master" }
kaspa-wrpc-client    = { git = "https://github.com/kaspanet/rusty-kaspa", branch = "master" }

[dev-dependencies]
tokio                  = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
vprogs-node-test-suite = { path = "../test-suite" }

kaspa-consensus-core = { git = "https://github.com/kaspanet/rusty-kaspa", branch = "master" }
